#!/bin/bash

# js
ls src/js | while read x; 
do
	echo $x
	fish -c "compiler --language_in ECMASCRIPT5 --js src/js/$x --js_output_file assets/js/$x"
done

# css
ls src/css | while read x; 
do
	echo $x
	fish -c "yui-compressor src/css/$x -o assets/css/$x"
done

rm -rf hsperfdata_ming/
